permissions:
  contents: write

name: Build binaries
on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t gitgrope -f .Dockerfile .

      - name: Tag the image with current version
        run: |
          docker tag gitgrope:latest ghcr.io/sharkfoursix/gitgrope:${{github.ref_name}}
          docker tag gitgrope:latest ghcr.io/sharkfoursix/gitgrope:latest
  
      - name: Push to ghcr.io
        run: |
          docker push ghcr.io/sharkfoursix/gitgrope:${{github.ref_name}}
          docker push ghcr.io/sharkfoursix/gitgrope:latest
